<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LuckyDangle</AssemblyName>
    <RootNamespace>LuckyDangle</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\Dangles\maneki_neko.png" />
</ItemGroup>
</Project>
